# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convert.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 130, 450, 450))
        self.groupBox.setObjectName("groupBox")
        self.ImageLabel = QtWidgets.QLabel(self.groupBox)
        self.ImageLabel.setGeometry(QtCore.QRect(10, 20, 435, 435))
        self.ImageLabel.setText("")
        self.ImageLabel.setObjectName("ImageLabel")
        self.widget = QCameraViewfinder(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 20, 435, 435))
        self.widget.setObjectName("widget")
        self.FileButton = QtWidgets.QPushButton(self.centralwidget)
        self.FileButton.setGeometry(QtCore.QRect(30, 40, 171, 61))
        self.FileButton.setObjectName("FileButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(540, 130, 450, 450))
        self.groupBox_2.setObjectName("groupBox_2")
        self.ResultLabel = QtWidgets.QLabel(self.groupBox_2)
        self.ResultLabel.setGeometry(QtCore.QRect(10, 20, 435, 435))
        self.ResultLabel.setText("")
        self.ResultLabel.setObjectName("ResultLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 310, 72, 41))
        self.label.setObjectName("label")
        self.ConvertButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConvertButton.setGeometry(QtCore.QRect(780, 40, 191, 61))
        self.ConvertButton.setIconSize(QtCore.QSize(20, 20))
        self.ConvertButton.setObjectName("ConvertButton")
        self.CameraButton = QtWidgets.QPushButton(self.centralwidget)
        self.CameraButton.setGeometry(QtCore.QRect(290, 40, 171, 61))
        self.CameraButton.setObjectName("CameraButton")
        self.CaptureButton = QtWidgets.QPushButton(self.centralwidget)
        self.CaptureButton.setGeometry(QtCore.QRect(550, 40, 171, 61))
        self.CaptureButton.setObjectName("CaptureButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1007, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人脸图像动漫化系统"))
        self.groupBox.setTitle(_translate("MainWindow", "初始图片窗口"))
        self.FileButton.setText(_translate("MainWindow", "选择文件"))
        self.groupBox_2.setTitle(_translate("MainWindow", "结果图片窗口"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">→</span></p></body></html>"))
        self.ConvertButton.setText(_translate("MainWindow", "开始转换"))
        self.CameraButton.setText(_translate("MainWindow", "摄像头拍摄"))
        self.CaptureButton.setText(_translate("MainWindow", "立即拍摄"))
from PyQt5.QtMultimediaWidgets import QCameraViewfinder


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
